pipeline {
    agent any

    tools {
        nodejs "NodeJS"
    }

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'rm -rf node_modules package-lock.json'
                sh 'npm install --ignore-scripts=false'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm run test -- --run'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
    }
}
